steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '-g', '@angular/cli']
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'UI'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'UI'
    args: ['run', 'build']
  - name: gcr.io/glass-approach-204914/firebase
    dir: 'UI'
    args: ['deploy', '--project=glass-approach-204914', '--only=hosting']

options:
  logging: CLOUD_LOGGING_ONLY
